# Día 1 — Python: estructuras de datos + Pandas fundamentos
### Preparación entrevista técnica Ebury (Treasury/ALM)

Objetivo de hoy: que crear, filtrar y explorar datos con Python/pandas te salga **sin pensar**. No es teoría abstracta — cada ejemplo usa datos de transacciones tipo Treasury (divisa, importe, contraparte, fecha), para que te acostumbres al vocabulario que vas a ver el lunes.

Estructura: teoría breve → ejercicio (con `# TODO`) → solución en la celda siguiente. Intenta resolver el TODO tú antes de mirar la solución.

## Parte 1 — Estructuras de datos base

### Listas
Colección ordenada y mutable. Es la estructura que más vas a usar para guardar secuencias de valores.

In [1]:
import datetime

import numpy as np
from numpy.matlib import zeros

divisas = ["USD", "GBP", "JPY", "EUR"]
divisas.append("CHF")
print(divisas)
print(divisas[0])       # primer elemento
print(divisas[-1])      # último elemento
print(divisas[1:3])     # slicing: del índice 1 al 2

['USD', 'GBP', 'JPY', 'EUR', 'CHF']
USD
CHF
['GBP', 'JPY']

### Diccionarios
Pares clave-valor. Muy usados para representar un registro (por ejemplo, una transacción) o para mapear divisa → tipo de cambio.

In [2]:
tipos_cambio = {"USD": 1.08, "GBP": 0.86, "JPY": 161.2}
tipos_cambio["CHF"] = 0.94   # añadir clave nueva
print(tipos_cambio["USD"])
print(tipos_cambio.get("AUD", "no disponible"))   # .get evita KeyError si no existe
print(tipos_cambio.keys())
print(tipos_cambio.values())
print(tipos_cambio.items())

1.08
no disponible
dict_keys(['USD', 'GBP', 'JPY', 'CHF'])
dict_values([1.08, 0.86, 161.2, 0.94])
dict_items([('USD', 1.08), ('GBP', 0.86), ('JPY', 161.2), ('CHF', 0.94)])

### Tuplas y sets (más breve, pero conviene reconocerlos)
- **Tupla**: como una lista, pero inmutable — `(1, 2, 3)`. Se usa para datos que no deben cambiar.
- **Set**: colección sin duplicados y sin orden — útil para saber, por ejemplo, cuántas divisas distintas hay en un dataset.

In [3]:
lista_con_repetidos = ["USD", "EUR", "USD", "GBP", "EUR"]
divisas_unicas = set(lista_con_repetidos)
print(divisas_unicas)
print(len(divisas_unicas))   # cuántas divisas distintas hay

{'EUR', 'USD', 'GBP'}
3

### Comprensiones de listas y diccionarios
Esto es importante — en una entrevista en vivo, escribir una comprensión en vez de un bucle explícito demuestra fluidez real.

In [4]:
importes = [1000, -500, 2300, -150, 800]

# forma "larga" con bucle
positivos_bucle = []
for x in importes:
    if x > 0:
        positivos_bucle.append(x)

# forma "pythónica" con comprensión de lista — practica escribir esto de memoria
positivos = [x for x in importes if x > 0]
print(positivos)

# comprensión de diccionario
cuadrados = {x: x**2 for x in range(5)}
print(cuadrados)

[1000, 2300, 800]
{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

### Ejercicio 1.1
Tienes una lista de diccionarios, cada uno representando una transacción. Escribe una comprensión de lista que devuelva **solo los importes en USD**.

In [5]:
transacciones = [
    {"divisa": "USD", "importe": 100000},
    {"divisa": "EUR", "importe": 50000},
    {"divisa": "USD", "importe": 25000},
    {"divisa": "GBP", "importe": 30000},
    {"divisa": "USD", "importe": 75000},
]

# TODO: usa una comprensión de lista para obtener los importes solo de las transacciones en USD
importes_usd = None  # tu código aquí

print(importes_usd)

None

**Solución 1.1** (no mires hasta intentarlo)

In [6]:
# Method 1:
importes_usd2=[]
for x in transacciones:
    if x["divisa"]=="USD":
        importes_usd2.append(x["importe"])
print(importes_usd2)
print(f"Sum of importes 2 is ",sum(importes_usd2))
# Method 2:
importes_usd=[x["importe"] for x in transacciones if x["divisa"]=="USD"]
print(importes_usd)
print(f"Sum of importes is ",sum(importes_usd))

# Create a dictionary with both answers
dict_importes=[
    {"Method":importes_usd2, "Sum":sum(importes_usd2)},
    {"Method":importes_usd, "Sum":sum(importes_usd)}
]

[100000, 25000, 75000]
Sum of importes 2 is  200000
[100000, 25000, 75000]
Sum of importes is  200000

### Ejercicio 1.2
Sigue usando la lista `transacciones` del Ejercicio 1.1. Escribe una comprensión de lista que devuelva **las divisas** (pueden salir repetidas) de las transacciones cuyo importe sea mayor a 40.000.

In [7]:
# TODO: usa una comprensión de lista
divisas_grandes = None  # tu código aquí

divisas_grandes=[x["divisa"] for x in transacciones if x["importe"]>=40000]

print(divisas_grandes)
print(set(divisas_grandes))

['USD', 'EUR', 'USD']
{'EUR', 'USD'}

**Solución 1.2** (no mires hasta intentarlo)

In [8]:
divisas_grandes = [t["divisa"] for t in transacciones if t["importe"] > 40000]
print(divisas_grandes)

# si quieres las divisas sin repetir, basta con envolver el resultado en set()
print(set(divisas_grandes))

['USD', 'EUR', 'USD']
{'EUR', 'USD'}

### Ejercicio 1.3 (integrador — combina dos comprensiones)
Escribe una **comprensión de diccionario** que mapee cada divisa distinta presente en `transacciones` a la **suma total** de los importes de esa divisa.

Pista: necesitas anidar dos comprensiones — usa `{t["divisa"] for t in transacciones}` para sacar las divisas únicas, y dentro del value usa `sum(...)` con otra comprensión que filtre por esa divisa.

In [9]:
# TODO: comprensión de diccionario anidada
suma_por_divisa = None  # tu código aquí

# Conseguir la transacción total por divisa

## My method:
transaction_currency={}
diff_curr=list(set([t["divisa"] for t in transacciones]))
print(diff_curr)

for i in range(len(diff_curr)): # from 0 to le(diff_curr)
    transaction_currency[i]=[]
    for j in transacciones:
        if j["divisa"]==diff_curr[i]:
            transaction_currency[i].append(j["importe"])
print(transaction_currency)
sum_transactions_currency=[sum(transaction_currency[i]) for i in range(len(transaction_currency))]
suma_divisa={"Currency":diff_curr, "Sum": sum_transactions_currency}
print(suma_divisa)


## Method 2



## AI method:

['EUR', 'USD', 'GBP']
{0: [50000], 1: [100000, 25000, 75000], 2: [30000]}
{'Currency': ['EUR', 'USD', 'GBP'], 'Sum': [50000, 200000, 30000]}

**Solución 1.3**

In [10]:
suma_por_divisa = {
    d: sum(t["importe"] for t in transacciones if t["divisa"] == d)
    for d in {t["divisa"] for t in transacciones}
}
print(suma_por_divisa)

{'EUR': 50000, 'USD': 200000, 'GBP': 30000}

> **Nota:** el orden de las claves en el diccionario resultante puede variar entre ejecuciones, porque viene de iterar un `set` (los sets no garantizan orden). Si en la entrevista te piden un orden determinista, envuelve las claves en `sorted(...)`.

## Parte 2 — Funciones

Repaso rápido de sintaxis, con foco en lo que probablemente necesites: funciones con valores por defecto, y `*args`/`**kwargs` (menos crítico, pero puede aparecer).

In [11]:
def convertir_a_eur(importe, divisa, tipos_cambio, base="EUR"):
    """Convierte un importe desde su divisa original a EUR usando un diccionario de tipos de cambio."""
    if divisa == base:
        return importe
    return importe / tipos_cambio[divisa]

tipos_cambio = {"USD": 1.08, "GBP": 0.86}
print(convertir_a_eur(100000, "USD", tipos_cambio))
print(convertir_a_eur(50000, "EUR", tipos_cambio))

92592.59259259258
50000

### Ejercicio 2.1
Escribe una función `clasificar_importe(importe)` que devuelva `"grande"` si el importe absoluto es mayor a 100.000, `"medio"` si está entre 10.000 y 100.000, y `"pequeño"` en el resto de casos.

In [12]:
# TODO: escribe la función aquí
def clasificar_importe(importe):
    importe_abs=abs(importe)
    if importe_abs>100000:
        return "grande"
    elif importe_abs>10000 and importe_abs<100000:
        return "medio"
    else:
        return "pequeño"

print(clasificar_importe(150000))  # esperado: "grande"
print(clasificar_importe(50000))   # esperado: "medio"
print(clasificar_importe(500))     # esperado: "pequeño"

grande
medio
pequeño

**Solución 2.1**

In [13]:
def clasificar_importe(importe):
    importe_abs = abs(importe)
    if importe_abs > 100000:
        return "grande"
    elif importe_abs >= 10000:
        return "medio"
    else:
        return "pequeño"

print(clasificar_importe(150000))
print(clasificar_importe(50000))
print(clasificar_importe(500))

grande
medio
pequeño

## Parte 3 — Pandas: fundamentos

Ahora vamos a lo que más vas a usar el lunes. Primero, la diferencia clave:
- **Series**: una columna, con índice.
- **DataFrame**: una tabla completa, como una hoja de Excel o el resultado de una consulta SQL.

Vamos a crear un dataset de transacciones de tesorería — muy parecido al tipo de datos con el que probablemente trabajes en la prueba.

In [14]:
import pandas as pd
import numpy as np

data = {
    "id_transaccion": range(1, 11),
    "divisa": ["USD", "EUR", "GBP", "USD", "JPY", "EUR", "USD", "GBP", "USD", "EUR"],
    "importe": [100000, -50000, 30000, -25000, 500000, 75000, -120000, 45000, 60000, -30000],
    "contraparte": ["Cliente_A", "Cliente_B", "Cliente_A", "Cliente_C", "Cliente_B",
                     "Cliente_A", "Cliente_D", "Cliente_C", "Cliente_B", "Cliente_A"],
    "fecha_vencimiento": pd.to_datetime([
        "2026-09-05", "2026-09-15", "2026-10-01", "2026-08-30", "2026-11-20",
        "2026-09-10", "2026-08-28", "2026-12-01", "2026-09-25", "2026-10-15"
    ])
}

df = pd.DataFrame(data)
df

   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
1               2    EUR   -50000   Cliente_B        2026-09-15
2               3    GBP    30000   Cliente_A        2026-10-01
3               4    USD   -25000   Cliente_C        2026-08-30
4               5    JPY   500000   Cliente_B        2026-11-20
5               6    EUR    75000   Cliente_A        2026-09-10
6               7    USD  -120000   Cliente_D        2026-08-28
7               8    GBP    45000   Cliente_C        2026-12-01
8               9    USD    60000   Cliente_B        2026-09-25
9              10    EUR   -30000   Cliente_A        2026-10-15

### Exploración básica — siempre haz esto primero con cualquier dataset nuevo

In [15]:
df.head()        # primeras 5 filas

   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
1               2    EUR   -50000   Cliente_B        2026-09-15
2               3    GBP    30000   Cliente_A        2026-10-01
3               4    USD   -25000   Cliente_C        2026-08-30
4               5    JPY   500000   Cliente_B        2026-11-20

In [16]:
df.info()         # tipos de datos y nulos por columna

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_transaccion     10 non-null     int64
 1   divisa             10 non-null     str
 2   importe            10 non-null     int64
 3   contraparte        10 non-null     str
 4   fecha_vencimiento  10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 532.0 bytes

In [17]:
df.describe()     # estadísticas de columnas numéricas

       id_transaccion        importe    fecha_vencimiento
count        10.00000      10.000000                   10
mean          5.50000   58500.000000  2026-09-30 00:00:00
min           1.00000 -120000.000000  2026-08-28 00:00:00
25%           3.25000  -28750.000000  2026-09-06 06:00:00
50%           5.50000   37500.000000  2026-09-20 00:00:00
75%           7.75000   71250.000000  2026-10-11 12:00:00
max          10.00000  500000.000000  2026-12-01 00:00:00
std           3.02765  168770.883481                  NaN

In [18]:
df.shape          # (filas, columnas)

(10, 5)

In [19]:
df.dtypes         # tipo de dato de cada columna

id_transaccion                int64
divisa                          str
importe                       int64
contraparte                     str
fecha_vencimiento    datetime64[us]
dtype: object

### Selección: `.loc` vs `.iloc`
- `.loc` selecciona por **etiqueta** (nombre de columna, valor de índice).
- `.iloc` selecciona por **posición** (como un índice numérico de lista).

Esta es una de las confusiones más típicas — practícala hasta que sea automática.

In [20]:
print(df.loc[0, "divisa"])        # fila con índice 0, columna "divisa"
print(df.iloc[0, 1])              # primera fila, segunda columna (posición)

print(df.loc[0:2])                # filas con índice 0,1,2 (incluye el final con .loc)
print(df.iloc[0:2])               # filas en posición 0,1 (excluye el final, como slicing normal)

USD
USD
   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
1               2    EUR   -50000   Cliente_B        2026-09-15
2               3    GBP    30000   Cliente_A        2026-10-01
   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
1               2    EUR   -50000   Cliente_B        2026-09-15

### Filtrado booleano
Esto es, probablemente, lo que más vas a usar el lunes. Piensa en ello como el `WHERE` de SQL.

In [21]:
# Transacciones en USD
usd = df[df["divisa"] == "USD"]
eurA=df[(df["divisa"]=="EUR") & (df["contraparte"]=="Cliente_A")]
print(usd)
print(eurA)

   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
3               4    USD   -25000   Cliente_C        2026-08-30
6               7    USD  -120000   Cliente_D        2026-08-28
8               9    USD    60000   Cliente_B        2026-09-25
   id_transaccion divisa  importe contraparte fecha_vencimiento
5               6    EUR    75000   Cliente_A        2026-09-10
9              10    EUR   -30000   Cliente_A        2026-10-15

In [22]:
# Transacciones en USD Y con importe positivo (usa & y paréntesis, no "and")
usd_positivas = df[(df["divisa"] == "USD") & (df["importe"] > 0)]
print(usd_positivas)

   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
8               9    USD    60000   Cliente_B        2026-09-25

In [24]:
# Transacciones en USD O en GBP (usa | , no "or")
usd_o_gbp = df[(df["divisa"] == "USD") | (df["divisa"] == "GBP")]
print(usd_o_gbp)

# forma más limpia con .isin() cuando comparas contra varios valores
usd_o_gbp_v2 = df[df["divisa"].isin(["USD", "GBP"])]
print(usd_o_gbp_v2)

   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
2               3    GBP    30000   Cliente_A        2026-10-01
3               4    USD   -25000   Cliente_C        2026-08-30
6               7    USD  -120000   Cliente_D        2026-08-28
7               8    GBP    45000   Cliente_C        2026-12-01
8               9    USD    60000   Cliente_B        2026-09-25
   id_transaccion divisa  importe contraparte fecha_vencimiento
0               1    USD   100000   Cliente_A        2026-09-05
2               3    GBP    30000   Cliente_A        2026-10-01
3               4    USD   -25000   Cliente_C        2026-08-30
6               7    USD  -120000   Cliente_D        2026-08-28
7               8    GBP    45000   Cliente_C        2026-12-01
8               9    USD    60000   Cliente_B        2026-09-25

### Tipos de datos y conversión (`dtypes`, `.astype()`)

In [25]:
# Si una columna numérica llega como texto (muy común en CSVs reales), hay que convertirla
df_ejemplo = pd.DataFrame({"importe_texto": ["1000", "2500", "3200"]})
print(df_ejemplo.dtypes)

df_ejemplo["importe_num"] = df_ejemplo["importe_texto"].astype(float)
print(df_ejemplo.dtypes)

importe_texto    str
dtype: object
importe_texto        str
importe_num      float64
dtype: object

### Ejercicio 3.1
Usando el DataFrame `df` de transacciones:
1. Filtra las transacciones donde el importe sea negativo (salidas de caja).
2. De esas, quédate solo con las que vencen antes del 1 de octubre de 2026.
3. Cuenta cuántas hay.

In [31]:
# TODO: resuelve los 3 pasos aquí
salidas = None
salidas_antes_oct = None
n_salidas = None

salidas=df[df["importe"]<0]
salidas_antes_oct=df[(df["importe"]<0) & (df["fecha_vencimiento"] < "2026-10-01")]
salidas_antes_oct2=salidas[salidas["fecha_vencimiento"]<"2026-10-01"]
print(salidas_antes_oct)
print(salidas_antes_oct2)
n_salidas=np.shape(salidas_antes_oct)[0]
print(f"Number of outputs is: ",n_salidas)

   id_transaccion divisa  importe contraparte fecha_vencimiento
1               2    EUR   -50000   Cliente_B        2026-09-15
3               4    USD   -25000   Cliente_C        2026-08-30
6               7    USD  -120000   Cliente_D        2026-08-28
   id_transaccion divisa  importe contraparte fecha_vencimiento
1               2    EUR   -50000   Cliente_B        2026-09-15
3               4    USD   -25000   Cliente_C        2026-08-30
6               7    USD  -120000   Cliente_D        2026-08-28
Number of outputs is:  3

**Solución 3.1**

In [30]:
salidas = df[df["importe"] < 0]
salidas_antes_oct = salidas[salidas["fecha_vencimiento"] < "2026-10-01"]
n_salidas = len(salidas_antes_oct)

print(salidas_antes_oct)
print(f"Número de salidas antes de octubre: {n_salidas}")

   id_transaccion divisa  importe contraparte fecha_vencimiento
1               2    EUR   -50000   Cliente_B        2026-09-15
3               4    USD   -25000   Cliente_C        2026-08-30
6               7    USD  -120000   Cliente_D        2026-08-28
Número de salidas antes de octubre: 3

### Ejercicio 3.2 (integrador — combina todo lo de hoy)
Escribe una función `resumen_por_divisa(df)` que devuelva un DataFrame con, para cada divisa: el importe total y el número de transacciones. Pista: vas a necesitar algo más que lo visto hoy (`groupby`) — es un adelanto de mañana, pero intenta razonar cómo lo harías con lo que ya sabes (por ejemplo, con un bucle sobre `df["divisa"].unique()` y filtrado booleano dentro).

In [55]:
# TODO: inténtalo con un enfoque "manual" (bucle + filtrado), sin usar groupby todavía

# Method 1:
def resumen_por_divisa_manual(df):
    unique_curr=df["divisa"].unique()
    sum_unique_curr=np.zeros(len(unique_curr))
    transactions=np.zeros(len(unique_curr))
    for i in range(len(unique_curr)):
        sum_unique_curr[i]=sum(df["importe"][df["divisa"]==unique_curr[i]])
        transactions[i]=len(df[df["divisa"]==unique_curr[i]])
    summary=pd.DataFrame(unique_curr,columns=["divisa"])
    summary["Sum"]=sum_unique_curr
    summary["Transactions"]=transactions

    return summary
print(resumen_por_divisa_manual(df))

# Method 2:
def resumen_por_divisa_manual2(df):
    final_summary=[]
    for i in df["divisa"].unique():
        subset=df[df["divisa"]==i]
        suma=sum(subset["importe"])
        trans=len(subset)
        final_summary.append({
            "Currency": i,
            "Sum":suma,
            "Transactions":trans
        })
        final_summary_df=pd.DataFrame(final_summary)
    return final_summary_df

print(resumen_por_divisa_manual2(df))

  divisa       Sum  Transactions
0    USD   15000.0           4.0
1    EUR   -5000.0           3.0
2    GBP   75000.0           2.0
3    JPY  500000.0           1.0
  Currency     Sum  Transactions
0      USD   15000             4
1      EUR   -5000             3
2      GBP   75000             2
3      JPY  500000             1

**Solución 3.2 (enfoque manual, sin groupby)**

In [37]:
def resumen_por_divisa_manual(df):
    filas = []
    for divisa in df["divisa"].unique():
        subset = df[df["divisa"] == divisa]
        filas.append({
            "divisa": divisa,
            "importe_total": subset["importe"].sum(),
            "n_transacciones": len(subset)
        })
    return pd.DataFrame(filas)

print(resumen_por_divisa_manual(df))

  divisa  importe_total  n_transacciones
0    USD          15000                4
1    EUR          -5000                3
2    GBP          75000                2
3    JPY         500000                1

> Mañana (Día 2) verás que esto mismo se hace en **una sola línea** con `df.groupby("divisa")["importe"].agg(["sum", "count"])`. Es importante que hoy entiendas el "por qué" manualmente, para que mañana `groupby` te parezca solo un atajo, no magia.

---
## Parte 4 — Operaciones de DataFrame que vas a usar constantemente

Tenías razón en pararte a pensar en esto: los DataFrames son el objeto central de casi toda la prueba. Esto es lo que faltaba para que el manejo básico esté realmente completo, antes de pasar a groupby/merge mañana.

### Añadir, eliminar y renombrar columnas

In [54]:
df["importe_abs"] = df["importe"].abs()             # nueva columna a partir de otra
df["es_salida"] = df["importe"] < 0                   # nueva columna booleana

df = df.drop(columns=["importe_abs"])                 # eliminar una columna
df = df.rename(columns={"contraparte": "cliente"})    # renombrar columna(s)

print(df.columns.tolist())

['id_transaccion', 'divisa', 'importe', 'cliente', 'fecha_vencimiento', 'es_salida']

### Ordenar, valores únicos y conteos
`sort_values` y `value_counts` son de las funciones que más vas a usar para "hacerte una idea rápida" de un dataset nuevo.

In [56]:
df_ordenado = df.sort_values("importe", ascending=False)
print(df_ordenado.head(3))

print(df["divisa"].unique())        # valores distintos
print(df["divisa"].nunique())       # cuántos valores distintos hay
print(df["divisa"].value_counts())  # cuántas veces aparece cada valor — muy útil para explorar rápido

   id_transaccion divisa  importe    cliente fecha_vencimiento  es_salida
4               5    JPY   500000  Cliente_B        2026-11-20      False
0               1    USD   100000  Cliente_A        2026-09-05      False
5               6    EUR    75000  Cliente_A        2026-09-10      False
<StringArray>
['USD', 'EUR', 'GBP', 'JPY']
Length: 4, dtype: str
4
divisa
USD    4
EUR    3
GBP    2
JPY    1
Name: count, dtype: int64

### `.apply()` con funciones/lambda
Para transformar una columna con lógica que no tiene una función de pandas ya hecha. Úsalo cuando de verdad lo necesites — para operaciones simples, las operaciones vectorizadas (como `df["importe"].abs()`) son más rápidas y más "pandas-idiomáticas" que `.apply()`.

In [63]:
df["categoria_importe"] = df["importe"].apply(clasificar_importe)  # reutilizando la función del Ejercicio 2.1
print(df[["importe", "categoria_importe"]])

# Another way
categoria=[]
for i in df["importe"]:
    categoria.append(clasificar_importe(i))
df["categoria_importe2"]=categoria
df.drop(columns="categoria_importe2")

# con lambda, para algo puntual que no merece una función aparte
df["importe_miles"] = df["importe"].apply(lambda x: x / 1000)
print(df[["importe", "importe_miles"]].head(3))

   importe categoria_importe
0   100000             medio
1   -50000             medio
2    30000             medio
3   -25000             medio
4   500000            grande
5    75000             medio
6  -120000            grande
7    45000             medio
8    60000             medio
9   -30000             medio
   importe  importe_miles
0   100000          100.0
1   -50000          -50.0
2    30000           30.0

### El error más típico bajo presión: `SettingWithCopyWarning`
Esto le pasa a todo el mundo alguna vez, y en una entrevista en vivo puede ponerte nervioso si no sabes qué significa. Ocurre cuando modificas un DataFrame que en realidad es una "vista" (un subconjunto filtrado) de otro, y pandas no está seguro de si debe modificar el original o no.

In [ ]:
# Esto puede lanzar un SettingWithCopyWarning:
usd_mal = df[df["divisa"] == "USD"]
# usd_mal["revisado"] = True   # <- esta línea generaría el warning si la descomentas

# La forma correcta: usa .copy() explícitamente cuando vayas a modificar un subconjunto
usd_bien = df[df["divisa"] == "USD"].copy()
usd_bien["revisado"] = True
print(usd_bien[["divisa", "revisado"]])

> **Regla práctica para el lunes**: si vas a filtrar un DataFrame y luego modificarlo (añadir columnas, cambiar valores), añade `.copy()` justo después del filtrado. Te ahorra el warning y, más importante, te ahorra el bug real de modificar sin querer el DataFrame original.

### Ejercicio 4.1 (integrador de la Parte 4)
Usando `df`:
1. Crea una copia filtrada solo con las transacciones que vencen en septiembre de 2026.
2. Añade una columna `dias_restantes` con los días entre hoy (usa `pd.Timestamp("2026-08-26")` como "hoy") y la fecha de vencimiento.
3. Ordena el resultado por `dias_restantes` de menor a mayor.

In [71]:
# TODO: resuelve los 3 pasos
septiembre = None
resultado_final = None

dfc=df.copy()
septiembre=dfc[(dfc["fecha_vencimiento"]<"2026-10-01") & (dfc["fecha_vencimiento"]>"2026-09-01")]
septiembre["Remaining Days"]=septiembre["fecha_vencimiento"]-pd.Timestamp("2026-08-26")
resultado_final=septiembre.sort_values("Remaining Days", ascending=True)

print(resultado_final)

   id_transaccion divisa  importe    cliente fecha_vencimiento  es_salida  \
0               1    USD   100000  Cliente_A        2026-09-05      False
5               6    EUR    75000  Cliente_A        2026-09-10      False
1               2    EUR   -50000  Cliente_B        2026-09-15       True
8               9    USD    60000  Cliente_B        2026-09-25      False

  categoria_importe  importe_miles categoria_importe2 Remaining Days
0             medio          100.0              medio        10 days
5             medio           75.0              medio        15 days
1             medio          -50.0              medio        20 days
8             medio           60.0              medio        30 days

**Solución 4.1**

In [68]:
septiembre = df[(df["fecha_vencimiento"] >= "2026-09-01") & (df["fecha_vencimiento"] < "2026-10-01")].copy()
septiembre["dias_restantes"] = (septiembre["fecha_vencimiento"] - pd.Timestamp("2026-08-26")).dt.days
resultado_final = septiembre.sort_values("dias_restantes")

print(resultado_final[["id_transaccion", "divisa", "fecha_vencimiento", "dias_restantes"]])

   id_transaccion divisa fecha_vencimiento  dias_restantes
0               1    USD        2026-09-05              10
5               6    EUR        2026-09-10              15
1               2    EUR        2026-09-15              20
8               9    USD        2026-09-25              30

---
## Resumen del Día 1 — lo que deberías dominar ahora
- Crear y manipular listas, diccionarios, sets, y escribir comprensiones sin pensar demasiado.
- Escribir funciones simples con condicionales.
- Crear un DataFrame, explorarlo (`.head()`, `.info()`, `.describe()`, `.shape`, `.dtypes`).
- Diferencia entre `.loc` y `.iloc`.
- Filtrado booleano con `&`, `|`, `.isin()` — y **nunca usar `and`/`or` con Series de pandas**, es un error muy común bajo presión.
- Convertir tipos con `.astype()`.
- Añadir/eliminar/renombrar columnas, `sort_values`, `value_counts`, `unique`/`nunique`.
- `.apply()` con funciones o lambda, sabiendo cuándo NO usarlo (operaciones vectorizadas son mejores).
- Qué es y cómo evitar el `SettingWithCopyWarning` con `.copy()`.

Si todo esto te ha salido con fluidez, estás listo para el Día 2 (groupby, pivot_table, merge, fechas).